# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md","2013-11-14-sample.md","2013-11-14-sample-2.md","2013-11-15-configuration.md","2013-11-15-hello-world.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: rambharlia
google_analytics: Ram Bharlia
title: Ram Bharlia
comments: true
defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Ram Bharlia

description: Stylish Jekyll Theme
author:
  name: Ram Bharlia
  email: rambharlia007@gmail.com
  github: rambharlia007
  twitter: rambharlia
  pinterest: 
  linkedin: ram-bharlia-73b2b0101
  bio: full stack dotnet developer
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
